# Версия синтаксиса
version: "3"

# В этом блоке описание контейнеров, которые буду запускаться
services:
    # Котейнер с ngnix
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: myapp/nginx
        container_name: websserver
        # Проброс портов
        ports:
            - "80:80"
        volumes:
            - ./code:/data/mysite.local
        networks:
            - app-network

    # Контейнер с PHP-FPM, назовем его app
    app:
        # Если нет секции с build, то система будет искать его образ в репозитории
        build:
            context: ./fpm
            dockerfile: Dockerfile
        image: myapp/php # имя будущего контейнера
        container_name: app # имя контейнера после запуска
        volumes:
            - ./code:/data/mysite.local
        # Мы можем создать для контейнеров внутреннюю сеть
        networks:
            - app-network

    #Docker networks
networks:
    app-network:
        driver: bridge
